name: Build Artifacts

env:
  x86arch: $"D:\a\git_compiler_test\git_compiler_test\CommandTaskAnalizer\bin\x86\Release\CommandTaskAnalizer.exeCommandTaskAnalizer.exe"
  x64arch: $"D:\a\git_compiler_test\git_compiler_test\CommandTaskAnalizer\bin\x64\Release\CommandTaskAnalizer.exeCommandTaskAnalizer.exe"
  projectName: "CommandTaskAnalizer.sln"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build for x86 (32-bit)
      run: |
        msbuild ${{ env.projectName }} /p:Configuration=Release /p:Platform=x86 /p:TargetFrameworkVersion=v4.6 
        
    - name: Archive x86 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: x86-artifact
        path: ${{ env.x86arch }}

    - name: Build for x64 (64-bit)
      run: |
        msbuild ${{ env.projectName }} /p:Configuration=Release /p:Platform=x64 /p:TargetFrameworkVersion=v4.6 

    - name: Archive x64 artifacts
      uses: actions/upload-artifact@v2
      with:
        name: x64-artifact
        path: ${{ env.x64arch }}